#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Models.Manager.PageModels;
    
    #line default
    #line hidden
    using Piranha.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Edit.cshtml")]
    public partial class _Areas_Manager_Views_Page_Edit_cshtml : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.EditModel>
    {
        public _Areas_Manager_Views_Page_Edit_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("Head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 170), Tuple.Create("\"", 226)
, Tuple.Create(Tuple.Create("", 176), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.form.js")
, 176), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 273), Tuple.Create("\"", 332)
, Tuple.Create(Tuple.Create("", 279), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.regions.js")
, 279), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 379), Tuple.Create("\"", 441)
, Tuple.Create(Tuple.Create("", 385), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.attachment.js")
, 385), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 488), Tuple.Create("\"", 552)
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.media.dialog.js")
, 494), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 599), Tuple.Create("\"", 659)
, Tuple.Create(Tuple.Create("", 605), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/jquery.comments.js")
, 605), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 706), Tuple.Create("\"", 774)
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(Href("~/res.ashx/areas/manager/content/js/ext/jquery.equalheights.js")
, 712), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    \t\tvar folderId = \"\";\r\n    \t\tvar deletemsg = \"");

            
            #line 14 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        Write(Piranha.Resources.Page.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        $(document).ready(function () {\r\n            // UI Stuff\r\n         " +
"   $(\"#Page_Title\").focus();\r\n            $(\'.first-row .box\').equalHeights();\r\n" +
"\r\n");

            
            #line 21 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Action == EditModel.ActionType.ATTACHMENTS) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            $(\'#btn_attachments\').click();\r\n            ");

WriteLiteral("\r\n");

            
            #line 25 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"
            $(""#Page_ParentId"").change(function () {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();
                var site_tree = $(""#Page_SiteTreeInternalId"").val();

                $.get(""");

            
            #line 34 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid + ""&site_tree="" + site_tree, function (data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");

            
            #line 43 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&group_id="" + group_id, function(data) {
                    $(""#disable-groups"").html(data);
                });
            });

            $('#btnMove').click(function () {
                $('#placement-edit').slideToggle('fast');
                $(this).toggleClass('active');
                return false;
            });

            new piranha.comment('");

            
            #line 54 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Model.Page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', \'comment-notification\', \'pnl-comments .inner\');\r\n            \r\n            new" +
" piranha.media(\'btn_attach\', \'boxContent\', function (a) {\r\n                // St" +
"ore folder id so we can open the same folder next time.\r\n                folderI" +
"d = a.ParentId;\r\n\r\n                // Add the attachment\r\n                $(\"#tb" +
"l-attachments\").append(\r\n                    \'<tr data-id=\"\' + a.Id + \'\">\' +\r\n  " +
"                      \'<td><img src=\"\' + a.ThumbnailUrl + \'/50\" /></td>\' +\r\n    " +
"                    \'<td>\' + a.DisplayName + \'</td>\' +\r\n                        " +
"\'<td>\' + a.Type + \'</td>\' +\r\n                        \'<td class=\"buttons three\">" +
"\' +\r\n                            \'<a class=\"icon up marg\"></a>\' +\r\n             " +
"               \'<a class=\"icon down marg\"></a>\' +\r\n                            \'" +
"<a class=\"icon delete\"></a></td>\' +\r\n                    \'</tr>\');\r\n            " +
"});\r\n\r\n            $(\".delete\").click(function () {\r\n            \treturn confirm" +
"(deletemsg);\r\n            });\r\n        });\r\n\r\n        //\r\n        // Hides all e" +
"ditors on the page. This callback is called from jquery.attachments.js\r\n        " +
"//\r\n        function hideEditors() {\r\n            $(\"#pageregions .input, #globa" +
"lregions .input\").hide();\r\n            $(\"#regionbuttons button\").removeClass(\"a" +
"ctive\");\r\n            $(\"#attachments\").hide();\r\n\r\n            $(\"#regions .regi" +
"on-body\").hide();\r\n            $(\"#regionbuttons button\").removeClass(\"active\");" +
"\r\n            $(\"#attachments\").hide();\r\n        }\r\n\r\n        //\r\n        // Thi" +
"s callback is called from jquery.attachments.js before form submit.\r\n        //\r" +
"\n        function addAttachmentData(index, val) {\r\n            $(\"#attachment_da" +
"ta\").append(\r\n                    \'<input id=\"Page_Attachments_\' + index +\r\n    " +
"                \'_\" name=\"Page.Attachments[\' + index +\r\n                    \']\" " +
"type=\"hidden\" value=\"\' + $(val).attr(\"data-id\") + \'\" />\');\r\n        }\r\n    </scr" +
"ipt>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");

            
            #line 104 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n        <ul>\r\n            <li><a");

WriteLiteral(" class=\"save submit\"");

WriteLiteral(">");

            
            #line 108 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSaveDraft);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            
            
            #line default
            #line hidden
            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew)
            {
                if (Model.SiteTree != null && !string.IsNullOrEmpty(Model.SiteTree.HostNames))
                {
                    foreach (var hostName in Model.SiteTree.HostNames.Split(','))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5031), Tuple.Create("\"", 5132)
            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5038), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.GetSiteUrl(hostName)
            
            #line default
            #line hidden
, 5038), false)
            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
      , Tuple.Create(Tuple.Create("", 5087), Tuple.Create<System.Object, System.Int32>(Url.GetPermalink(Model.Page.Permalink, true)
            
            #line default
            #line hidden
, 5087), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(" class=\"preview\"");

WriteLiteral(">");

            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                 Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    }
                }
                else
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5327), Tuple.Create("\"", 5420)
            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5334), Tuple.Create<System.Object, System.Int32>(Piranha.WebPages.WebPiranha.GetSiteUrl()
            
            #line default
            #line hidden
, 5334), false)
            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5375), Tuple.Create<System.Object, System.Int32>(Url.GetPermalink(Model.Page.Permalink, true)
            
            #line default
            #line hidden
, 5375), false)
);

WriteLiteral(" target=\"preview\"");

WriteLiteral(" class=\"preview\"");

WriteLiteral(">");

            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                     Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 124 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteLiteral(" class=\"publish\"");

WriteLiteral(">");

            
            #line 125 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Model.Page.Published == DateTime.MinValue ? Piranha.Resources.Global.ToolbarPublish : Piranha.Resources.Global.ToolbarUpdate);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 126 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 127 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 5925), Tuple.Create("\"", 5984)
            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5932), Tuple.Create<System.Object, System.Int32>(Url.Action("unpublish", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 5932), false)
);

WriteLiteral(" class=\"unpublish\"");

WriteLiteral(">");

            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 129 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 130 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6201), Tuple.Create("\"", 6257)
            
            #line 131 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6208), Tuple.Create<System.Object, System.Int32>(Url.Action("revert", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6208), false)
);

WriteLiteral(" class=\"revert\"");

WriteLiteral(">");

            
            #line 131 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 132 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 133 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew && Model.CanDelete && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6472), Tuple.Create("\"", 6528)
            
            #line 134 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6479), Tuple.Create<System.Object, System.Int32>(Url.Action("delete", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6479), false)
);

WriteLiteral(" class=\"delete\"");

WriteLiteral(">");

            
            #line 134 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 135 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 136 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (String.IsNullOrEmpty(ViewBag.ReturnUrl)) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6689), Tuple.Create("\"", 6744)
            
            #line 137 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6696), Tuple.Create<System.Object, System.Int32>(Url.Action("index", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6696), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 137 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 138 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6847), Tuple.Create("\"", 6872)
            
            #line 139 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6854), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnUrl
            
            #line default
            #line hidden
, 6854), false)
);

WriteLiteral(" class=\"back\"");

WriteLiteral(">");

            
            #line 139 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 140 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a");

WriteAttribute("href", Tuple.Create(" href=\"", 6968), Tuple.Create("\"", 7022)
            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6975), Tuple.Create<System.Object, System.Int32>(Url.Action("edit", new { id = Model.Page.Id })
            
            #line default
            #line hidden
, 6975), false)
);

WriteLiteral(" class=\"refresh\"");

WriteLiteral(">");

            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

WriteLiteral("            ");

            
            #line 142 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n");

});

WriteLiteral("\r\n");

            
            #line 149 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]) ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n");

WriteLiteral("    ");

            
            #line 151 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 152 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 153 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeInternalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 154 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.OriginalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 155 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 156 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 157 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 159 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 161 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 164 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 165 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.UpdatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 167 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 168 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 169 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 170 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 171 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 172 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 173 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 173 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (Model.IsSite) {
    
            
            #line default
            #line hidden
            
            #line 174 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Title));

            
            #line default
            #line hidden
            
            #line 174 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 175 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
            
            #line 175 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 176 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
            
            #line 176 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 177 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
            
            #line 177 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 179 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Piranha.Application.Current.IsMvc) {
    
            
            #line default
            #line hidden
            
            #line 180 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PageView));

            
            #line default
            #line hidden
            
            #line 180 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 182 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Hidden("returl", (string)ViewBag.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"draft\"");

WriteLiteral(" name=\"draft\"");

WriteLiteral(" value=\"true\"");

WriteLiteral(" />\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"org_parentid\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8771), Tuple.Create("\"", 8799)
            
            #line 184 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8779), Tuple.Create<System.Object, System.Int32>(Model.Page.ParentId
            
            #line default
            #line hidden
, 8779), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"first-row\"");

WriteLiteral(">\r\n    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 8846), Tuple.Create("\"", 8936)
            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8854), Tuple.Create<System.Object, System.Int32>(!String.IsNullOrEmpty(Model.Template.Preview.ToString()) ? "grid_9" : "grid_12"
            
            #line default
            #line hidden
, 8854), false)
);

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 189 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>");

            
            #line 193 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 195 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 196 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>");

            
            #line 198 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 200 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 201 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li");

WriteLiteral(" class=\"protected\"");

WriteLiteral(">");

            
            #line 203 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Permalink != null && !String.IsNullOrEmpty(Model.Permalink.Name)) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 205 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
            
            #line 205 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                               Write(Url.GetPermalink(Model.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 206 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p><i>");

            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");

            
            #line 208 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 210 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                        ");

            
            #line 211 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteLiteral(" class=\"locked\"");

WriteLiteral("></a>\r\n                    </li>\r\n                    <li>\r\n                     " +
"   <label>");

            
            #line 215 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button");

WriteLiteral(" class=\"btn right\"");

WriteLiteral(" id=\"btnMove\"");

WriteLiteral(">");

            
            #line 216 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                          Write(Piranha.Resources.Global.Move);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 217 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 217 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.Page.IsStartpage) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");

            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Page.Seqno > 1 ? @Piranha.Resources.Global.PlacementAfter : @Piranha.Resources.Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");

            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                                                   Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");

            
            #line 219 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");

            
            #line 220 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 221 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"placement-edit\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 223 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_ParentId\"");

WriteLiteral(" name=\"Page.ParentId\"");

WriteLiteral(">\r\n");

            
            #line 226 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 226 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (var p in Model.Parents) {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 11510), Tuple.Create("\"", 11523)
            
            #line 227 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 11518), Tuple.Create<System.Object, System.Int32>(p.Id
            
            #line default
            #line hidden
, 11518), false)
);

            
            #line 227 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(p.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 228 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 229 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n");

WriteLiteral("                            ");

            
            #line 232 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(" id=\"div-seqno\"");

WriteLiteral(">\r\n                                <select");

WriteLiteral(" id=\"Page_Seqno\"");

WriteLiteral(" name=\"Page.Seqno\"");

WriteLiteral(">\r\n");

            
            #line 235 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 235 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 foreach (var s in Model.Siblings) {

            
            #line default
            #line hidden
WriteLiteral("                                <option");

WriteAttribute("value", Tuple.Create(" value=\"", 12069), Tuple.Create("\"", 12085)
            
            #line 236 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 12077), Tuple.Create<System.Object, System.Int32>(s.Seqno
            
            #line default
            #line hidden
, 12077), false)
);

            
            #line 236 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 236 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 237 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </li>\r\n                </ul>\r\n" +
"");

            
            #line 243 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                    <li>\r\n");

WriteLiteral("                        ");

            
            #line 246 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaTitle, Piranha.Resources.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 248 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 249 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 249 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaTitle)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 250 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 251 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                    <l" +
"i>\r\n");

WriteLiteral("                        ");

            
            #line 255 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaDescription, Piranha.Resources.SiteTree.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 257 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.SiteTree.MetaDescription, new { @rows = 5 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 258 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 258 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaDescription)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 259 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 260 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                </ul>\r" +
"\n");

            
            #line 264 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 268 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 268 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!String.IsNullOrEmpty(Model.Template.Preview.ToString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"grid_3\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box pagetemplate\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 271 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(!Model.IsSite ? Model.Template.Name : Model.SiteTree.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"edit\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 274 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 279 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <div");

WriteLiteral(" class=\"grid_12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box main-content\"");

WriteLiteral(">\r\n            <table>\r\n                <tr>\r\n                    <td");

WriteLiteral(" class=\"tools\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 14276), Tuple.Create("\"", 14355)
, Tuple.Create(Tuple.Create("", 14284), Tuple.Create("btn-content", 14284), true)
            
            #line 288 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 14295), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 14296), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-content\"");

WriteLiteral(">");

            
            #line 288 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 289 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 289 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteAttribute("class", Tuple.Create(" class=\"", 14517), Tuple.Create("\"", 14597)
, Tuple.Create(Tuple.Create("", 14525), Tuple.Create("btn-settings", 14525), true)
            
            #line 290 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 14537), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "active" : ""
            
            #line default
            #line hidden
, 14538), false)
);

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-settings\"");

WriteLiteral(">");

            
            #line 290 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                               Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 291 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 292 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-properties\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-properties\"");

WriteLiteral(">");

            
            #line 293 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                       Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 294 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 295 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"btn-comments\"");

WriteLiteral(">\r\n");

            
            #line 297 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 297 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  
                                    var count = Model.Comments.Where(c => c.Status == Piranha.Entities.Comment.CommentStatus.New).Count() ;
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                                <span ");

            
            #line 300 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(count == 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(" id=\"comment-notification\" class=\"notification\">");

            
            #line 300 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"pnl-comments\"");

WriteLiteral(">");

            
            #line 301 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n");

            
            #line 303 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                            ");

            
            #line 304 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             foreach (var ext in Model.Extensions) {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a");

WriteLiteral(" href=\"#\"");

            
            #line 306 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(ExtensionManager.Current.GetIconPathByType(ext.Type) != "" ? "style=background-image:url('" + 
                                Url.Content(ExtensionManager.Current.GetIconPathByType(ext.Type)) + "')" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");

            
            #line 307 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                       Write(ExtensionManager.Current.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");

WriteLiteral("                                    ");

            
            #line 308 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(ExtensionManager.Current.GetNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");

            
            #line 311 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </td>\r\n                    <td" +
">\r\n                        <div");

WriteLiteral(" id=\"pnl-content\"");

WriteAttribute("class", Tuple.Create(" class=\"", 16342), Tuple.Create("\"", 16429)
, Tuple.Create(Tuple.Create("", 16350), Tuple.Create("main", 16350), true)
, Tuple.Create(Tuple.Create(" ", 16354), Tuple.Create("content-editor", 16355), true)
            
            #line 315 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 16369), Tuple.Create<System.Object, System.Int32>(Model.Action != EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 16370), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" id=\"regionbuttons\"");

WriteLiteral(" class=\"buttons\"");

WriteLiteral(">\r\n");

            
            #line 318 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 318 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     for (int n = 0; n < Model.Regions.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                        <button");

WriteAttribute("id", Tuple.Create(" id=\"", 16689), Tuple.Create("\"", 16741)
            
            #line 319 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 16694), Tuple.Create<System.Object, System.Int32>(Html.Raw("btn_" + Model.Regions[n].InternalId)
            
            #line default
            #line hidden
, 16694), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 16742), Tuple.Create("\"", 16785)
, Tuple.Create(Tuple.Create("", 16750), Tuple.Create("btn", 16750), true)
            
            #line 319 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               , Tuple.Create(Tuple.Create("", 16753), Tuple.Create<System.Object, System.Int32>(n > 0 ? "" : " active"
            
            #line default
            #line hidden
, 16753), false)
, Tuple.Create(Tuple.Create(" ", 16778), Tuple.Create("region", 16779), true)
);

WriteLiteral(">");

            
            #line 319 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                            Write(Model.Regions[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 320 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" id=\"btn_attachments\"");

WriteAttribute("class", Tuple.Create(" class=\"", 16923), Tuple.Create("\"", 16978)
, Tuple.Create(Tuple.Create("", 16931), Tuple.Create("btn", 16931), true)
            
            #line 321 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 16934), Tuple.Create<System.Object, System.Int32>(Model.Regions.Count == 0 ? " active" : ""
            
            #line default
            #line hidden
, 16934), false)
);

WriteLiteral(">");

            
            #line 321 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                    Write(Piranha.Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2");

WriteLiteral(" id=\"section-title\"");

WriteLiteral(">");

            
            #line 323 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n");

            
            #line 326 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 326 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 if (Model.Regions.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"regions\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 328 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");

            
            #line 330 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" id=\"attachments\"");

WriteLiteral(" ");

            
            #line 331 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Model.Regions.Count > 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 332 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n");

            
            #line 336 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 336 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-settings\"");

WriteAttribute("class", Tuple.Create(" class=\"", 17893), Tuple.Create("\"", 17965)
, Tuple.Create(Tuple.Create("", 17901), Tuple.Create("main", 17901), true)
            
            #line 337 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
, Tuple.Create(Tuple.Create(" ", 17905), Tuple.Create<System.Object, System.Int32>(Model.Action == EditModel.ActionType.SEO ? "" : "hidden"
            
            #line default
            #line hidden
, 17906), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 338 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n                                    <li>\r\n");

WriteLiteral("                                        ");

            
            #line 342 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 344 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.DropDownListFor(m => m.Page.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 345 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.DisabledGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" id=\"disable-groups\"");

WriteLiteral(" class=\"block\"");

WriteLiteral(">\r\n");

            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               var dGroups = Model.Groups.Where(g => g.Value != Guid.Empty.ToString()).ToList() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                            ");

            
            #line 348 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Partial("Partial/GroupList", new Piranha.Models.Manager.PageModels.GroupListModel() { 
                                                Groups = Model.DisableGroups, Page = Model.Page }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </li>\r\n                                    <li>\r\n");

WriteLiteral("                                        ");

            
            #line 353 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");

            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");

            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
"     <li>");

            
            #line 356 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral("> \r\n");

WriteLiteral("                                            ");

            
            #line 358 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.Keywords, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 359 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 359 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Keywords)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 360 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 361 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n");

WriteLiteral("                                        ");

            
            #line 363 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>");

            
            #line 365 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 367 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Page.Description, new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 368 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            
            
            #line default
            #line hidden
            
            #line 368 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Description)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span");

WriteLiteral(" class=\"notification\"");

WriteLiteral(">");

            
            #line 369 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");

            
            #line 370 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n");

WriteLiteral("                                        ");

            
            #line 372 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 374 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 374 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowController) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 375 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageController,
                                            Piranha.Application.Current.IsMvc ? Piranha.Resources.Page.Route : Piranha.Resources.Page.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 378 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : "Page" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 379 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 381 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

            
            #line 382 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Piranha.Application.Current.IsMvc && Model.Template.ShowView) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 383 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 385 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageView, new { @placeholder = !String.IsNullOrEmpty(Model.Template.View) ? Model.Template.View : "Index" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 386 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 388 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    ");

            
            #line 389 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowRedirect) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 390 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 392 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

WriteLiteral("                                        ");

            
            #line 393 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");

            
            #line 395 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 399 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 400 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-properties\"");

WriteLiteral(" class=\"main hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 402 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n");

            
            #line 405 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 405 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 for (int n = 0; n < Model.Properties.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");

            
            #line 406 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 407 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 408 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 409 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 410 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 411 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 412 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].CreatedBy));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                        ");

            
            #line 413 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div");

WriteLiteral(" class=\"input\"");

WriteLiteral(">\r\n");

WriteLiteral("                                            ");

            
            #line 415 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </li>\r\n");

            
            #line 417 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");

            
            #line 421 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 422 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" id=\"pnl-comments\"");

WriteLiteral(" class=\"main content-editor hidden\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 424 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div");

WriteLiteral(" class=\"inner region-body\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 426 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                           Write(Html.Partial("~/Areas/Manager/Views/Comment/List.cshtml", Model.Comments));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");

            
            #line 429 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");

            
            #line 430 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"grid_3 hidden\"");

WriteLiteral(">\r\n");

            
            #line 438 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 438 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"box expandable\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"title\"");

WriteLiteral("><h2>");

            
            #line 440 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div");

WriteLiteral(" class=\"inner optional\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"list\"");

WriteLiteral(">\r\n                <li>");

            
            #line 443 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 444 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.LastPublished > DateTime.MinValue ? Model.Page.LastPublished.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 445 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 446 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.Published > DateTime.MinValue ? Model.Page.Published.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 447 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 447 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");

            
            #line 448 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small");

WriteLiteral(" class=\"right\"");

WriteLiteral(">");

            
            #line 448 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");

            
            #line 452 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 454 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Foot", () => {

WriteLiteral("\r\n <div");

WriteLiteral(" id=\"boxContent\"");

WriteLiteral(" class=\"floatbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bg\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" style=\"min-width: 510px;min-height:260px;\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
